### ISSUE TITLE
example for reading incoming USDT transactions

### ISSUE THREAD

**Issue by naelbw** [olifanton/ton#20]
Hi
I want to monitor a wallet address for incoming USDT transactions and read the comments

i’m stuck at the point where i read transactions but it’s raw data and i don’t know where to go from here

**Comment by kendol07** [comment]
https://tonapi.io/v2/accounts/0:03b4b1d574df8af4f74f24c590d7085b93c03631bb6a21b54e0730b2e9a80ff4/events?limit=10

use your wallet address  -> 0:03b4b1d574df8af4f74f24c590d7085b93c03631bb6a21b54e0730b2e9a80ff4
