### ISSUE TITLE
Retrieving Transaction Hash Post-Transaction

### ISSUE THREAD

**Issue by kendol07** [olifanton/ton#21]
Could you please explain how I can retrieve the transaction hash after sending a transaction using your library?

**Comment by romanzaycev** [comment]
You can get a hash of an external message that will be sent to the blockchain (your wallet's smart contract) via Transport:

```php
$externalMessage = $wallet->createTransferMessage([
    // Transfers array...
], new TransferOptions(/** Seqno... */));
// Message hash
$externalMessageHash = Bytes::bytesToBase64($externalMessage->sign($keyPair->secretKey)->hash());
$transport->sendMessage($externalMessage, $keyPair->secretKey);
```

Note that Message and Transaction in TON are different things: https://docs.ton.org/develop/smart-contracts/guidelines/message-delivery-guarantees

Thus, it is impossible to get the hash of the transaction in advance.

You need to use the indexer API (Toncenter, Tonapi) to search for transactions by message hash and account.

**Comment by kendol07** [comment]
After testing, this method worked for me.
This sends the transaction and also extracts the hash.

$result = $toncenter->sendBocReturnHash($extMessage->sign($kp->secretKey)->toBoc(false));
$hash = bin2hex(base64_decode($result->result['hash']));

**Comment by alicompu** [comment]
> After testing, this method worked for me. This sends the transaction and also extracts the hash.
> 
> $result = $toncenter->sendBocReturnHash($extMessage->sign($kp->secretKey)->toBoc(false)); $hash = bin2hex(base64_decode($result->result['hash']));

Thanks, This worked
