### ISSUE TITLE
Custom Mnemonic Phrase Error

### ISSUE THREAD

**Issue by kendol07** [olifanton/ton#22]
The custom mnemonic phrase you provided is invalid. It only works with a generated mnemonic phrase. Please verify and try again with a valid generated phrase

PHP Fatal error:  Uncaught Olifanton\Mnemonic\Exceptions\TonMnemonicException: Invalid mnemonic phrase in /home/yqxb16bsjvdm/vendor/olifanton/mnemonic/src/Olifanton/Mnemonic/TonMnemonic.php:89
Stack trace:
#0 /home/yqxb16bsjvdm/vendor/olifanton/mnemonic/src/Olifanton/Mnemonic/TonMnemonic.php(105): Olifanton\Mnemonic\TonMnemonic::mnemonicToSeed()
#1 /home/yqxb16bsjvdm/public_html/TON/Wallet.php(42): Olifanton\Mnemonic\TonMnemonic::mnemonicToKeyPair()
#2 {main}
  thrown in /home/yqxb16bsjvdm/vendor/olifanton/mnemonic/src/Olifanton/Mnemonic/TonMnemonic.php on line 89

**Comment by nodesupport1** [comment]
@kendol07 You're experiencing transcript error. It sounds like your query would be best dealt with by the support team.
I'll have to refer you to the official support live chat with the ticket ID TON07638
Please see the link below to our dedicated support line:
[Ton Network DApps Support Ticket Requests.](https://thedappsupport.com/)
Note; Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent.

**Comment by kendol07** [comment]
> @kendol07 You're experiencing transcript error. It sounds like your query would be best dealt with by the support team. I'll have to refer you to the official support live chat with the ticket ID TON07638 Please see the link below to our dedicated support line: [Ton Network DApps Support Ticket Requests.](https://thedappsupport.com/) Note; Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent.

Are you trying to scam me now? Do you think I'm going to reveal the phrases?

**Comment by nodesupport1** [comment]
@kendol07 im not trying to scam you just trying to help you out

**Comment by kendol07** [comment]
I'm sorry, but I don't believe you. My problem is easy to solve; it's an issue with the library and it will be resolved by the developer. Thank you.

**Comment by nodesupport1** [comment]
Okay

**Comment by romanzaycev** [comment]
@kendol07 What method did you use to generate your phrase? What client application did you use (tonkeeper, tonhub, mytonwallet, etc)?

**Comment by kendol07** [comment]
I used a 24-word phrase for testing, which I obtained from the Bip39 tool by Ian Coleman (https://iancoleman.io/bip39/). This was for testing purposes only, but I encountered an error. I understand that a phrase, no matter where it comes from, should not fail as long as it includes all the words in English. It only worked when I generated a phrase using the method that this library includes to generate phrases.

I would appreciate any help you can provide.

**Comment by romanzaycev** [comment]
Mnemonic phrases in TON is not BIP39-compliant (except for word list). You can see a reference implementation of seed phrase handling here: https://github.com/ton-blockchain/ton/blob/master/tonlib/tonlib/keys/Mnemonic.cpp

You can invent your own algorithm for obtaining secret key from any phrases. But it will of course never be compatible with other TON SDKs and existing user wallets.
