### ISSUE TITLE
How to use the SDK to initiate ton transfers and USDT transfers? Where are the relevant sample codes?

### ISSUE THREAD

**Issue by xuanbin** [olifanton/ton#23]

**Comment by romanzaycev** [comment]
- https://github.com/olifanton/ton/blob/main/examples/wallets/send-transaction.php
- https://github.com/olifanton/ton/blob/main/examples/jettons/usdt-transfer.php

**Comment by xuanbin** [comment]
I am using a Tonkeeper wallet, and it appears that I can only access the wallet address but am unable to export the associated private key. Do you have any instructions on how to do this?

**Comment by SuprimeKebab** [comment]
You can back up your Tonkeeper wallet using a recovery phrase (mnemonic) and retrieve the keypair with Olifanton\Mnemonic\TonMnemonic::mnemonicToKeyPair.

**Comment by SuprimeKebab** [comment]
> I am using a Tonkeeper wallet, and it appears that I can only access the wallet address but am unable to export the associated private key. Do you have any instructions on how to do this?

You can back up your Tonkeeper wallet using a recovery phrase (mnemonic) and retrieve the keypair with `Olifanton\Mnemonic\TonMnemonic::mnemonicToKeyPair(array $mnemonicArray, ?string $password = null): KeyPair`
