### ISSUE TITLE
The error occurs when running the code in the test environment, but it doesn’t happen when I replace the constant USDT_JETTON_MINTER_ADDR with the address EQDOTr21oyFE5Aylolo0NxG9eNxSxPz0bW2OWzaswOrP7WTK. I’m not sure where to obtain this parameter specifically.

### ISSUE THREAD

**Issue by xuanbin** [olifanton/ton#25]
`define("USDT_JETTON_MINTER_ADDR", "EQCxE6mUtQJKFnGfaROTKOt1lZbDiiX1kCixRv7Nw2Id_sDs"); // `https://tonviewer.com/EQCxE6mUtQJKFnGfaROTKOt1lZbDiiX1kCixRv7Nw2Id_sDs`
$usdtRoot = JettonMinter::fromAddress(
    $transport,
    new Address(USDT_JETTON_MINTER_ADDR),
);`

**Comment by romanzaycev** [comment]
You are trying to use the USDT minter address from the main network.

There is no contract at this address on the test network. You can mint your test token in the test network and use it in your test environment instead of USDT.
